dataset:
  repo_id: IndiaTechTeamSL2/tictactoe
policy:
  type: act_lang
  device: cuda
  push_to_hub: true
  repo_id: IndiaTechTeamSL2/tictactoe-act-lang
batch_size: 64
steps: 25000
save_freq: 5000
output_dir: outputs/train/tictactoe_act_lang
job_name: tictactoe_act_lang
wandb:
  enable: false
